* art
** Kein Zaubertrank
  Jedes Kind weiss:
  kein bärtiger Mann
  in ganz Gallien (? $\rightarrow$ !)
  ist weiser
  als Mirakulix.

  Sie hingegen war,
  soweit auf der Seite sichtbar, 
  frisch
  und glatt rasiert.
  - Ich sage zu dir,
  schreibt sie,
  das atomare Chaos
  betrifft jede Zelle.

  Das stimmt nicht mal in ihrem Fall.
  Chemische Bindungen
  sind ziemlich stabil.

** Zell-null-lose
  Ich hab Mitleid mit meinem Saugroboter.
  Er findet seine Aufladezelle nicht mehr,
  dreht sich kopflos im Kreis.

  Fraglos läuft alles
  auf jeden Fall
  ganz rund im Moment
  bei mir.

  Gottseidank hat meine Hose
  einen Gummizug.

  Die Jeans wär mir grad zu eng.

* Mosaik
** Im Stadtpark
  Wie Youtube 
  ist er,
  mit Werbung:
  Stört plötzlich,
  bleibt bestimmt.

  bedauernswert
  aber
  ein abbuchabonnement
  bleibt wunsch
  ist unmöglich
  
** Taunusanlage
     Frankfurt im Spätherbst.

  Er,
  unrasiert,
  abgerissen,
  fragt,
  entgegenkommend,
  mein junges Ich:

  - Wo gehts zur Bundesbank?

  Ich weise weiter in seine Richtung.

  Sein Blick fixiert mich,
  sehnsüchtig,
  skeptisch, über
  fünfzigjährig.

  - Bürojob,
  oder?

  Ich nicke im Anzug
  und folge dem Wind.

  Er dagegen setzt den Schritt
  auf der andern Seite fort, um
  hier letzte D-Mark in Euro zu tauschen.
