* K J Ferner
** Fliegenpilz
   olles essn wos giftig is ;; giftig 4
   nua oi moi fliagnpüz zua jausn ;; jausn 3
   da foablust wegn warats ;; wegn 1
   mit de hollabisch um d'wettn ;; hollabisch 2
   
   schworzbeamund
   im oa spün de hummen auf ;; spün 3
   vabrumman se zwischn brennessl ;; zwischn 1
   und sauaompfa  
   ochtsome wegbegleita: klee, moos ;; moos 2
   und ondres krawialach ;; ondres 5
   i ko scho koa grea mea segn ;; segn 4

** Köhler
   da oide köhla wohnt ;; oide 1
   im hoizfaschlog ;; hoizfaschlog 5
   an da traubneichn ;; da 4
   de schief gwochsn ins fensta hängt ;; schief 3
   die zweige san dem köhla sei ;; zweige 2
   wäscheleine
   
   sunst siagt man kaum ;; kaum 3
   sei ruf is dahi ;; dahi 6
   zündla zischn de bama ;; zischn 2
   hinta seim ruckn ;; ruckn 1
   obwoi scho long koa rauch ;; koa 5
   mehr aus da köhlerei kummt ;; kummt 4

   luftvapesta sogn de umweltschütza ;; sogn 4
   de in de maulwurfsgrebn drinhockn ;;  maulwurfsgrebn 5
   natürlich mit volla rücksicht ;; volla 2
   ohne de viacha z'vastörn ;; viacha 3
   da köhla oba ko ned schlofn ;; schlofn 1

   schattn triabn sei iris ;; traibn 3
   und in seina haut ;; seina 2
   gliaht es feia ;; feia 1

** Schwammal
   de schwammal sterbm an leisn tod ;; schwammal 5
   woandas brennt da woid o ;;brennt 4
   de vicha sand auf da flucht ;; sand 1
   da rauch vaschliaßt ohrn und nosn ;; vaschliaßt 2
   und de lichtungen werdn weit ;; weit 3
   
   da köhla trogt gluat auf de wangerl ;; auf 3
   und de umwödschütza laufn durch de ;; laufn 2
   büsch
   und vasprenkln eana letztes quöwossa ;; letztes 5
   grillgeruch hengg in da luft ;; luft 4
   es brotn de vegl mit spitze schrei ;; vegl 1
   es pfiatn de äst a baba ;; baba 6
   
* Kloimhardt
** Kein Zaubertrank
  Jedes Kind weiss: ;; Kind 4
  kein bärtiger Mann ;; Mann 1
  in ganz Gallien ;; ganz 3
  ist weiser ;; ist 2
  als Miraculix.

  Sie hingegen war, ;; war 1
  soweit auf der Seite sichtbar, ;; soweit 2
  frisch
  und glatt rasiert. ;; glatt 3
  - Ich sage zu dir,
  schreibt sie,
  das atomare Chaos
  betrifft jede Zelle.

  Das stimmt nicht mal in ihrem Fall.
  Chemische Bindungen
  sind ziemlich stabil.
