* K J Ferner
** Fliegenpilz
   olles essn wos giftig is ;; giftig 4
   nua oi moi fliagnpüz zua jausn ;; jausn 3
   da foablust wegn warats ;; wegn 1
   mit de hollabisch um d'wettn ;; hollabisch 2
   
   schworzbeamund
   im oa spün de hummen auf ;; spün 3
   vabrumman se zwischn brennessl und sauaompfa ;; zwischn 1 
   ochtsome wegbegleita: klee, moos und ondres krawialach ;; moos 2
   i ko scho koa grea mea segn ;; segn 4

** Köhler
   da oide köhla wohnt ;; oide 1
   im hoizfaschlog ;; hoizfaschlog 5
   an da traubneichn ;; da 4
   de schief gwochsn ins fensta hängt ;; schief 3
   die zweige san dem köhla sei wäscheleine ;; zweige 2
   
   sunst siagt man kaum ;; kaum 3
   sei ruf is dahi ;; dahi 5
   zündla zischn de bama ;; zischn 2
   hinta seim ruckn ;; ruckn 1
   obwoi scho long koa rauch mehr aus da köhlerei kummt ;; kummt 4

   luftvapesta sogn de umweltschütza
   de in de maulwurfsgrebn drinhockn
   natürlich mit volla rücksicht
   ohne de viacha z'vastörn
   da köhla oba ko ned schlofn

   schattn triabn sei iris
   und in sein haut
   gliaht es feia
   
* Art
** Kein Zaubertrank
  Jedes Kind weiss: ;; Kind 4
  kein bärtiger Mann ;; Mann 1
  in ganz Gallien ;; ganz 3
  ist weiser ;; ist 2
  als Miraculix.

  Sie hingegen war, ;; war 1
  soweit auf der Seite sichtbar, ;; soweit 2
  frisch
  und glatt rasiert. ;; glatt 3
  - Ich sage zu dir,
  schreibt sie,
  das atomare Chaos
  betrifft jede Zelle.

  Das stimmt nicht mal in ihrem Fall.
  Chemische Bindungen
  sind ziemlich stabil.

** Zell-null-lose
  Ich hab Mitleid mit meinem Saugroboter.
  Er findet seine Aufladezelle nicht mehr,
  dreht sich kopflos im Kreis.

  Fraglos läuft alles
  auf jeden Fall
  ganz rund im Moment
  bei mir.

  Gottseidank hat meine Hose
  einen Gummizug.

  Die Jeans wär mir grad zu eng.

* Mosaik
** Im Stadtpark
  Wie Youtube 
  ist er,
  mit Werbung:
  Stört plötzlich,
  bleibt bestimmt.

  bedauernswert
  aber
  ein abbuchabonnement
  bleibt wunsch
  ist unmöglich
  
** Taunusanlage
  Frankfurt im Spätherbst.

  Er,
  unrasiert,
  abgerissen,
  fragt,
  entgegenkommend,
  mein junges Ich:

  - Wo gehts zur Bundesbank?

  Ich weise weiter in seine Richtung.

  Sein Blick fixiert mich,
  sehnsüchtig,
  skeptisch, über
  fünfzigjährig.

  - Bürojob,
  oder?

  Ich nicke im Anzug
  und folge dem Wind.

  Er dagegen setzt den Schritt
  auf der andern Seite fort, um
  hier letzte D-Mark in Euro zu tauschen.
  
* State
** d
   duda ho ;; ho 1
